input {
  tcp {
    port => 5044
    codec => json_lines
  }
}
filter {
  if [level] {
    mutate { rename => { "level" => "log_level" } }
  }
}
output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "repertorio-logs-%{+YYYY.MM.dd}"
  }
}
