spring:
  application:
    name: procesion-service
  datasource:
    url: jdbc:postgresql://localhost:5434/procesion_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    enabled: true
    schemas: public
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: procesion-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/semana-santa
          jwk-set-uri: http://keycloak:8180/realms/semana-santa/protocol/openid-connect/certs

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  api-docs:
    path: /v3/api-docs/procesion
  swagger-ui:
    path: /swagger-ui.html
    url: /v3/api-docs/procesion
  servers:
    - url: http://localhost:8080
      description: API Gateway
